### ISSUE TITLE
Works for ruru but not momo

### ISSUE THREAD

**Issue by scruel** [canyie/SettingsFirewall#2]
ruru v1.1.1 (15)
momo v4.4.41

With LSPosed, even with "System Framework" selected, MOMO will still show "enabled debug mode",
Select MOMO itself will be the same.
And IDK why, I can't select "Settings Provider", module will auto unselect it.

**Comment by canyie** [comment]
本模块只能拦截通过 Settings API 发起的查询，无法干扰到通过其他方式获得的数据。
